name: Build Windows Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag or Version name for the release (e.g. 12.0.1)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  build_windows_release:
    name: Build Windows Installer
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Determine Version
        id: version_step
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.tag_name }}" ]; then
            VERSION="${{ github.event.inputs.tag_name }}"
          else
            VERSION=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building Prism Sync release version: $VERSION"

      - name: Enter Visual Studio Developer shell
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          vsversion: 2022

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup vcpkg environment
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.1.*"
          version: "6.10.2"
          modules: "qtimageformats qtnetworkauth"

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake --preset windows_msvc `
            -DLauncher_UPDATER_GITHUB_REPO="https://github.com/snowtyler/PrismLauncher" `
            -DLauncher_BUILD_ARTIFACT="Setup"

      - name: Compile Release Build
        shell: pwsh
        run: |
          cmake --build --preset windows_msvc --config Release

      - name: Stage Install Files
        shell: pwsh
        run: |
          cmake --install build --config Release

          cd ${{ github.workspace }}
          Get-ChildItem install -Recurse | ForEach FullName | Resolve-Path -Relative | %{ $_.TrimStart('.\') } | %{ $_.TrimStart('install') } | %{ $_.TrimStart('\') } | Out-File -FilePath install/manifest.txt

      - name: Build NSIS Installer
        shell: pwsh
        env:
          NSCURL_VERSION: "v24.9.26.122"
          NSCURL_SHA256: "AEE6C4BE3CB6455858E9C1EE4B3AFE0DB9960FA03FE99CCDEDC28390D57CCBB0"
        run: |
          New-Item -Name NSISPlugins -ItemType Directory -Force
          Invoke-WebRequest https://github.com/negrutiu/nsis-nscurl/releases/download/"$env:NSCURL_VERSION"/NScurl.zip -OutFile NSISPlugins\NScurl.zip
          $nscurl_hash = (Get-FileHash NSISPlugins\NScurl.zip -Algorithm Sha256).Hash
          if ($nscurl_hash -ne "$env:NSCURL_SHA256") {
            Write-Error "NScurl.zip sha256 mismatch"
            exit 1
          }
          Expand-Archive -Path NSISPlugins\NScurl.zip -DestinationPath NSISPlugins\NScurl -Force

          cd install
          makensis -NOCD "${{ github.workspace }}/build/program_info/win_install.nsi"
          cd ${{ github.workspace }}

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}
          name: Prism Sync ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            PrismSync-Setup-*.exe
